# ----------------------- #
#      Main Configs       #
# ----------------------- #

baseurl: /
title: Hunter - find/download data
email: nicolas@rawdatahunter.com
description: Hunter allows you to find and download open datasets quickly and easily from your terminal. We work hard to index and sort the most useful datasets available for you!

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
relative_permalinks: true

# ----------------------- #
#      Collections        #
# ----------------------- #

